spring:
  application:
    name: Auction System
  datasource:
    url: jdbc:mysql://localhost:3306/auction_system
    username: test
    password: password
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 3f8f4debeee3a93af3ee723b9af18ce9c4b57c88987f3040bf553db4a808cb8b
  expiryInMs: 86400000

logging.level.org.springframework.security: TRACE
