app:
  jwt:
    issuer: https://github.com/VanshajSaxena
    expiryMs: 3600000 # 1 hour
    # Use a different & strong key for production
    secret: 3f8f4debeee3a93af3ee723b9af18ce9c4b57c88987f3040bf553db4a808cb8b
spring:
  application:
    name: Auction System
# Spring Doc
springdoc.packages-to-exclude: com.auction.system.controllers
# springdoc.swagger-ui.path: /swagger-ui.html
# springdoc.api-docs.path: /v3/api-docs
# Basic API Info
# springdoc.info.title: Auction System
